#!/usr/bin/env python3
"""
write and asynchronous listcomprehension that returns a list of floats
generated by the asyn_generator function from the 'o-asyn_generator' module.
"""

from typing import list
from importlib import_module as using 
async_generator = using('0-async_generator').async_generator


async def asyn_comprehension() ->[float]:
    """
    Asynchronous list comprehension that returns a list of floats
    generated by the async_generator function.

    Return:
    list[float]: a list of floats generated by the async_generator.
    """
    return [num asyn for num in asyn_generator()]
